### PR TITLE
Origin/feature/#26 doubles

### PR DESCRIPTION
**Pull request by Chfaeser**
Implemented the doubles feature
Method checkDouble compares the dice roll and returns a boolean (for identification purposes since the player is allowed to take another turn afterwards)
Added a counter for how many doubles a player rolled in a row (this is relevant for the jail function) 
Added a small UI Element to tell the Player if his roll was a double or not (this is to stop confusion if an 8 was rolled with two 4s or a 3 and a 5)

### CODE REVIEW

**Review by SgtGraf — COMMENTED** [review]
It would be nice if both outcomes of the roll were displayed on the screen, not only the sum.

**Comment by SgtGraf** [comment]
After getting a double, the "Doubles!" text doesn't disappear if you roll the dice again.

image

**Comment by SgtGraf** [comment]
App keeps crashing when buying a Street

**Comment by Chfaeser** [comment]
This PR has been redone due to version issues on my end. All the reviewed changes were implemented in the new PR and it has been merged via origin/feature/#26 doubles2 that has been reviewed again. 
This means Issue#26 is closed and this PR is redundant. For consistency reasons and the reviewers comments this PR will be kept and closed.

**Pull request closed without merging**
